Added plugins support
RD17/react-trumbowyg pull request #18
Opened 2019-03-24 04:10 UTC by tejash-jl

Now you can pass the extra parameter for the plugins, like the serverUrl for upload etc.
https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-upload

2019-03-24 11:52 UTC, Alex-D requested changes

2019-03-24 11:52 UTC, Alex-D commented on package.json
> +    "trumbowyg": "2.12.0"
Please let the `^`

2019-03-24 11:52 UTC, Alex-D commented on package.json
> +    "react-hot-loader": "^4.8.0",
Why all these new deps are needed?

2019-03-25 04:16 UTC, tejash-jl commented
I have removed the changes suggested. Please check.

2019-03-25 10:39 UTC, Alex-D approved these changes
LGTM :)

@sochix can you merge (squash) that?

2019-03-25 13:44 UTC, merged

2019-03-25 13:44 UTC, sochix commented
Thanks everyone! Merged!